### ISSUE TITLE
Readme unclear about how to map nested objects and arrays

### ISSUE THREAD

**Issue by aureliengervasi** [Maltcommunity/mongo-connector-postgresql#7] opened 2017-03-22 10:26 UTC
Thank you for updating the README and giving more detailed mapping examples. I tried to implement your suggested structure, but I bump against a few issues. I have a list of ObjectId nested in a list of objects in a collection. I think it is quite close to second example given in the README. 

```
{
    "author": "507f1f77bcf86cd799439011",
    "posts": [{
            "name": "Check out the mongo -> postgres connector",
            "tags": [
                    "Awesome",
                    "Article",
                    "Postgres"
            ]
    }]
}
```

if I use a similar mapping to the one suggested, I run into the following issues:

- the foreign key ```timeline_id``` has to be inserted into the table ```timeline_posts```
- the field ```_id``` from the table ```timeline_posts``` creates a Null Value error as it doesn't find a corresponding field in the mongoDB database. I have to remove this field to make it work.

If I stop here, I can successfully map the ```name``` field in a ```timeline_posts``` table. 

When I try to map also the nested ```tags```, with similar corrections (foreign key and _id ), I get an error linked to a missing id key...

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 621, in do_dump
    upsert_all(dm)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 607, in upsert_all
    mapped_ns, long_ts)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/doc_managers/postgresql_manager.py", line 176, in bulk_upsert
    self._bulk_upsert(documents, namespace)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/doc_managers/postgresql_manager.py", line 189, in _bulk_upsert
    sql_bulk_insert(cursor, self.mappings, namespace, document_buffer)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/doc_managers/sql.py", line 79, in sql_bulk_insert
    insert_document_arrays(collection, cursor, db, document, mapped_document, mappings, primary_key)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/doc_managers/sql.py", line 114, in insert_document_arrays
    sql_bulk_insert(cursor, mappings, "{0}.{1}".format(db, dest), linked_documents)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/doc_managers/sql.py", line 80, in sql_bulk_insert
    insert_scalar_arrays(collection, cursor, db, document, mapped_document, mappings, primary_key)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/doc_managers/sql.py", line 100, in insert_scalar_arrays
    linked_documents.append({fk: mapped_document[primary_key], value_field: value})
KeyError: u'id'
```

Here is my mapping translated for the second example:

```
{
    "my_mongo_database": {
            "timeline": {
                    "pk": "id",
                    "_id": {
                            "dest": "id",
                            "type": "TEXT"
                    },
                    "author": {
                            "type": "TEXT"
                    },
                    "posts": {
                            "type": "_ARRAY",
                            "dest": "timeline_posts",
                            "fk": "timeline_id"
                    }
            },
            "timeline_posts": {
                    "pk": "id",
                    "timeline_id": {
                            "dest":"timeline_id",
                            "type": "TEXT"
                    },                    
                    "name": {
                            "type": "TEXT"
                    },
                    "tags": {
                            "dest": "timeline_posts_tags",
                            "type": "_ARRAY_OF_SCALARS",
                            "fk": "timeline_post_id",
                            "valueField": "tag"
                    }
            },
            "timeline_posts_tags": {
                    "pk": "id",
                    "timeline_post_id": {
                            "dest":"timeline_post_id",
                            "type": "TEXT"
                    },   
                    "tag": {
                            "type": "TEXT"
                    }
            }
    }
}
```

I guess I got something wrong here... I would be happy to have your thoughts on that ! I guess there might be some clarifications to be done in the README as a consequence.

**Comment by pajachiet** [comment] 2017-03-31 10:35
Hi Maxime !
We still have an issue when mapping an array_of_scalars inside an array of document. 
The problem appears in sql.py, function insert_scalar_arrays, line 100
```python
linked_documents.append({fk: mapped_document[primary_key], value_field: value})
```

The error is related to the primary_key of the mapped_document, which does not exist. 
As the mapped_document is a linked_document generated by insert_document_arrays, no primary key exists in the Mongo Document. 

When the primary key does not exists, it is automatically generated by postgresql during insertion. cf postgresl_manager.py, function _init_schema, line 89
```python
if not pk_found:
    columns.append(pk_name + ' SERIAL CONSTRAINT ' + collection.upper() + '_PK PRIMARY KEY')
```

So the issue is : How do you get this postgresql-automatically-generated primary key in the mapped_document ?

A related issue : the insertion of the parent document (mapped_document, from which we need the primary key) happens after mapping the array_of_scalars (where we need the primary key).

So, a few questions : 
- Did we understand the issue correctly ? 
- Did you have a similar case where you had to map an array_of_scalars inside an array of document ?
- Otherwise, what would you recommend ?

Thanks a lot for your work. We hope to be able to contribute to this doc_manager in the future.

**Comment by pajachiet** [comment] 2017-03-31 16:36
We are implementing a hack, to generate ourselves the primary_key of imbricated tables. 
It seems to work (to be continued before we can PR).

**Comment by hlassiege** [comment] 2018-08-30 09:33
Hi, I close this issue as this project is now unsupported and replaced by https://github.com/Maltcommunity/mongo-postgresql-streamer

**Closed by hlassiege** 2018-08-30 09:33 UTC
